export const regions = [
  { id: 'us-gov-east-1', label: 'AWS GovCloud (US-East)' },
  { id: 'us-gov-west-1', label: 'AWS GovCloud (US)' },
  { id: 'ap-east-1', label: 'Asia Pacific (Hong Kong)' },
  { id: 'ap-south-1', label: 'Asia Pacific (Mumbai)' },
  { id: 'ap-northeast-1', label: 'Asia Pacific (Tokyo)' },
  { id: 'ap-northeast-3', label: 'Asia Pacific (Osaka-Local)' },
  { id: 'ap-northeast-2', label: 'Asia Pacific (Seoul)' },
  { id: 'ap-southeast-1', label: 'Asia Pacific (Singapore)' },
  { id: 'ap-southeast-2', label: 'Asia Pacific (Sydney)' },
  { id: 'ca-central-1', label: 'Canada (Central)' },
  { id: 'eu-central-1', label: 'EU (Frankfurt)' },
  { id: 'eu-north-1', label: 'EU (Stockholm)' },
  { id: 'eu-west-1', label: 'EU (Ireland)' },
  { id: 'eu-west-2', label: 'EU (London)' },
  { id: 'eu-west-3', label: 'EU (Paris)' },
  { id: 'me-south-1', label: 'Middle East (Bahrain)' },
  { id: 'sa-east-1', label: 'South America (Sao Paulo)' },
  { id: 'us-east-1', label: 'US East (N. Virginia)' },
  { id: 'us-east-2', label: 'US East (Ohio)' },
  { id: 'us-west-1', label: 'US West (N. California)' },
  { id: 'us-west-2', label: 'US West (Oregon)' },
];
